#! /bin/sh

# Kill all running applications before starting
killall -9 sxhkd dunst polybar compton udiskie polkit-gnome-au pa-applet nm-applet mpd easystroke flashfocus
# numlockx unclutter mpDris2 redshift

#bspc monitor -d १ २ ३ ४ ५ ६ ७ ८ ९ ०
#bspc monitor -d I II III IV V VI VII VIII IX X
# bspc monitor -d 一 二 三 四 五 六 七 八 九 十 
bspc monitor -d 1 2 3 4 5 6 7 8


bspc config border_width            6
bspc config window_gap              12
bspc config border_radius           12

bspc config split_ratio             0.50
bspc config borderless_monocle      false
bspc config gapless_monocle         false
bspc config focus_follows_pointer   true

bspc config normal_border_color     "#4D4D4D"
bspc config focused_border_color    "#FF5555"
# bspc config focused_border_color    "#E6E6E6"

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# Window rules
bspc rule -a Google-chrome desktop='^2' follow=on
bspc rule -a chromium desktop='^2' follow=on
bspc rule -a Firefox desktop='^2'  follow=on

bspc rule -a Code desktop='^3' follow=on

bspc rule -a Nautilus desktop='^4' follow=on
bspc rule -a Pcmanfm desktop='^4' follow=on
bspc rule -a Thunar desktop='^4' follow=on

bspc rule -a TelegramDesktop desktop='^6' follow=on

bspc rule -a Nvidia-settings state=floating focus=on floating=on
bspc rule -a alsamixer state=floating focus=on
bspc rule -a GParted state=floating focus=on
bspc rule -a Lxappearance state=floating focus=on
bspc rule -a nitrogen state=floating focus=on
bspc rule -a SimpleScreenRecorder state=floating focus=on
bspc rule -a Pulseffects state=floating focus=on
bspc rule -a Pulseaudio-equalizer-gtk state=floating focus=on
bspc rule -a Pavucontrol state=floating focus=on center=on

bspc rule -a OpenGL state=floating focus=on center=on

sxhkd &

dunst &
nitrogen --restore &
compton &
xfce4-power-manager &

udiskie &
# pa-applet &
nm-applet &

polybar bspbar &
easystroke &
xset b off &

mpd &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

sleep 5; notify-send -t 5000 "System Successfully STARTED"  